### ISSUE TITLE
"getTransltionOrderJobs" is terminating the script

### ISSUE THREAD

**Issue by ajaydwarkani** [gengo/gengo-python#67] opened 2016-06-06 23:19 UTC
"getTransltionOrderJobs" function call is terminating the script. see the below error.

**My current environment**
Python 2.7
Gengo Python library 0.1.28
Windows 10

``` Python
    response_order = self.gengo.getTranslationOrderJobs(id=order_id)
  File "D:\Python27\lib\site-packages\gengo\gengo.py", line 309, in get
    post_data, file_data)
  File "D:\Python27\lib\site-packages\gengo\gengo.py", line 407, in signAndRequestAPILatest
    sha1)
  File "D:\Python27\lib\hmac.py", line 136, in new
    return HMAC(key, msg, digestmod)
  File "D:\Python27\lib\hmac.py", line 75, in __init__
    self.outer.update(key.translate(trans_5C))
TypeError: character mapping must return integer, None or unicode
```

**Comment by hayate** [comment] 2016-06-07 00:00
could you post the whole script you wrote please?

**Comment by ajaydwarkani** [comment] 2016-06-07 16:17
Here is my code
```Python
gengo = Gengo(public_key, private_key, sandbox=True, debug=True)
order_id = "2263158"
response_order = gengo.getTranslationOrderJobs(id=order_id)
```
I have also tried converting the "**order_id**" to integer as follows "**int(order_id)**", but still getting the same error.

hope this helps.

**Comment by ajaydwarkani** [comment] 2016-06-08 00:05
Here is similar problem but different place in the script

I believe it’s something to do with **hmac.new** function call. Today I got error on another place in the code for private key hashing.

Where order_id = “29237” on sandbox.

```Python
    response_order = self.gengo.getTranslationOrderJobs(id=order_id)
  File "D:\Python27\lib\site-packages\gengo\gengo.py", line 309, in get
    post_data, file_data)
  File "D:\Python27\lib\site-packages\gengo\gengo.py", line 407, in signAndRequestAPILatest
    sha1)
  File "D:\Python27\lib\hmac.py", line 136, in new
    return HMAC(key, msg, digestmod)
  File "D:\Python27\lib\hmac.py", line 75, in __init__
    self.outer.update(key.translate(trans_5C))
TypeError: character mapping must return integer, None or Unicode
```

**Comment by hayate** [comment] 2016-06-08 00:20
@ajaydwarkani thank you for posting extra info.

unfortunately I cannot reproduce your issue on my linux environment.
From the information you posted I think that the HMAC or hash python internal call relies on some `dll` libraries that you are missing on windows or that python cannot find at run time.
I haven't used windows for a while but if I remember well python cryptography on windows relies on openssl.
Seems to be confirmed by this link: 
https://pypi.python.org/pypi/hashlib

Could you try to make sure you have all the required `dll` on your library path for python to find them?

**Comment by ajaydwarkani** [comment] 2016-06-08 05:46
@hayate 
I will give it a try. But this only started happening recently after I updated the code from github.

**Comment by ajaydwarkani** [comment] 2016-06-08 06:13
@hayate 
Please find the fix in the attached file. It seems like the HMAC function in Python 2.x don't take **bytes** or **Unicode** and it only accepts **str** (http://stackoverflow.com/a/20862445)

[gengo_hmac_fix.zip](https://github.com/gengo/gengo-python/files/304085/gengo_hmac_fix.zip)

**Comment by hayate** [comment] 2016-06-08 06:17
I see.
what version of the gengo library were you using before you updated the code from github.
BTW `pip install gengo` often is better that just cloning our repo, as `pip install gengo` will take care of installing dependencies too.

The reason why I am guessing that you are probably missing some `dll` on your windows is because the error is coming from the internals of python and not from Gengo library.

The source of the error seems to be here:
```python
File "D:\Python27\lib\hmac.py", line 75, in __init__
    self.outer.update(key.translate(trans_5C))
TypeError: character mapping must return integer, None or Unicode
```

If you did not change anything from your environment (re-install windows, upgrade windows etc.) except updating Gengo library than it means we introduced something in our library that has some dependency that you are missing, this dependency seems to be related with the digital signature of the payload, which by the way did not change.
It also means that reverting to the previous version of the library should remove the error, could you confirm this?

**Comment by ajaydwarkani** [comment] 2016-06-08 06:21
FYI, I did use ``pip install gengo`` to install gengo library.

Please see my above post for the code fix. It was due to passing unicode string and hmac function only accepts "str"

**Comment by kelvintaywl** [comment] 2016-06-08 06:41
@ajaydwarkani thanks for looking into the issue. would appreciate it if you could make a pull request against our repository for this fix then? 🙇  that way it is clear for all to see the code changes required and etc.

**Comment by kelvintaywl** [comment] 2016-06-08 06:48
it would appear your attempted fix would be [from gengo/gengo.py] :

```diff
-            query_hmac = hmac.new(Gengo.compatibletext(self.private_key),
+            query_hmac = hmac.new(self.private_key,
                                   Gengo.compatibletext(query_params['ts']),
                                   sha1)
             query_params['api_sig'] = query_hmac.hexdigest()
@@ -402,7 +402,7 @@ class Gengo(object):
             query_string = urlencode(sorted(query_params.items(),
                                             key=itemgetter(0)))
             if self.private_key is not None:
-                query_hmac = hmac.new(Gengo.compatibletext(self.private_key),
+                query_hmac = hmac.new(self.private_key,
                                       Gengo.compatibletext(query_params['ts']),
                                       sha1)
                 query_params['api_sig'] = query_hmac.hexdigest()
@@ -435,7 +435,7 @@ class Gengo(object):
     @staticmethod
     def compatibletext(text):
         if sys.version_info < (3, 0, 0) or isinstance(text, bytes):
-            return str(text)
+            return text
 
         return bytes(text, 'utf-8')
```

**Comment by ajaydwarkani** [comment] 2016-06-08 13:50
Sure I can create a pull request.

**Comment by narusemotoki** [comment] 2017-01-18 05:25
This is already fixed. Thank you. I close this issue.

**Closed by narusemotoki** 2017-01-18 05:25 UTC
